# -*- coding: utf-8 -*-
"""DisneyML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15B9ayDXTIfqhPqUibUqhFkwC0rDj2taf

# ML Movie Recommendation System using sklearn
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""Data is comprised of the top 10k rated TMDB movies"""

data =  pd.read_csv('/content/drive/MyDrive/Colab Notebooks/top10K-TMDB-movies.csv')

data = data[['id', 'title', 'overview', 'genre']]
data['tags'] = data['overview']
data = data.drop(columns=['overview'])

"""The Data being used for our Matrix are Tokenized Words from the each movies Description."""

cv=CountVectorizer(max_features=10000, stop_words='english')
vector=cv.fit_transform(data['tags'].values.astype('U')).toarray()
tagsSimilarity=cosine_similarity(vector)

def recommend(watched, watchedHistory):

    preferredGenresVector = getPreferredGenresVector(watchedHistory)

    preferredGenreSimilarity = cosine_similarity([preferredGenresVector], tagsSimilarity)[0]

    combinedWeightedSimilarity = (0.4 * tagsSimilarity) + (0.6 * preferredGenreSimilarity)

    index=data[data['title']==watched].index[0]
    distance = sorted(list(enumerate(combinedWeightedSimilarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[1:16]:
        print(data.iloc[i[0]].title)

def getPreferredGenresVector(watchedHistory):
    preferredGenres = []
    for movie in watchedHistory:
      preferredGenres.append(data[data['title']==movie]['genre'].values)

    genreText = ' '.join([str(genre[0]) for genre in preferredGenres])
    genreVector = cv.transform([genreText]).toarray()[0]


    return genreVector

"""**watchHistory**: Shows Previously Watched

**recommend**(*just_Watched_Show*, *watchHistory*): First parameter is the show you just watched.

"""

watchHistory = ['Your Name.', 'Spirited Away', 'Everything Everywhere All at Once', 'Singin\' in the Rain']
recommend('Iron Man', watchHistory)